### ISSUE TITLE
Multipart support

### ISSUE THREAD

**Issue by sdogruyol** [kostya/http_parser.cr#2]
Hey there,

This looks pretty awesome. How about adding ***multipart/form-data*** parsing to this?

**Comment by kostya** [comment]
this is just wrapper for c library, not sure that it supported

**Comment by sdogruyol** [comment]
I am aware of that. However we can improve this and add multipart parsing
which is missing from Crystal std http.

Wdyt?

**Comment by sdogruyol** [comment]
Hey there thanks for the support. Which another library are you talking about?

**Comment by kostya** [comment]
https://github.com/iafonov/multipart-parser-c

**Comment by sdogruyol** [comment]
@kostya that's a c library.

**Comment by kostya** [comment]
yes, supported by binding

**Comment by sdogruyol** [comment]
Yeah thanks a lot 👍
